name: CI

on:
  schedule:
    - cron: "0 2 * * *"

jobs:
  commit:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Auto Commit
        run: |
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          utc_time=$(date -u "+%Y-%m-%d %H:%M:%S UTC")
          export GIT_AUTHOR_NAME="${{ github.actor }}"
          export GIT_AUTHOR_EMAIL="${{ github.actor }}@users.noreply.github.com"
          export GIT_COMMITTER_NAME="actions-user"
          export GIT_COMMITTER_EMAIL="actions-user@users.noreply.github.com"
          git commit --allow-empty -m "$utc_time"
          git push
